# -*- coding: utf-8 -*-
"""UAE_cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKsZZJj7lY-Yhce_fSslls-NhkTBH_Vm
"""

# Cancer Outcome Disparities by Gender and Age in the UAE

# Upload dataset
from google.colab import files
uploaded = files.upload()  # Upload UAE cancer dataset

# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency, f_oneway
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression

# Load dataset
df = pd.read_csv("UAE cancer.csv")

# Convert date columns to datetime
date_cols = ['Diagnosis_Date', 'Treatment_Start_Date', 'Death_Date']
for col in date_cols:
    df[col] = pd.to_datetime(df[col], errors='coerce')

# Handle missing outcomes
df = df[df['Outcome'].notnull()]
df['Cause_of_Death'] = df['Cause_of_Death'].fillna("Unknown")

# One-hot encode categorical variables
categorical_cols = ['Gender', 'Cancer_Type', 'Cancer_Stage', 'Treatment_Type', 'Comorbidities',
                    'Smoking_Status', 'Ethnicity', 'Nationality', 'Emirate', 'Hospital', 'Primary_Physician']
df = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

# Normalize continuous variables
scaler = MinMaxScaler()
df[['Age', 'Weight', 'Height']] = scaler.fit_transform(df[['Age', 'Weight', 'Height']])

# Create original age and age groups
df['Original_Age'] = scaler.inverse_transform(df[['Age', 'Weight', 'Height']])[:, 0]
df['AgeGroup'] = pd.cut(df['Original_Age'], bins=[0, 39, 59, 120], labels=['Under 40', '40-59', '60+'])

# Recreate Gender column
df['Gender'] = np.where(df['Gender_Male'] == 1, 'Male', 'Female')

# Descriptive stats for Age by Gender and Outcome
print("\nDescriptive Statistics - Age by Gender and Outcome:")
print(df.groupby(['Gender', 'Outcome'])['Original_Age'].describe())

# Histogram of Age by Outcome
sns.histplot(data=df, x='Original_Age', hue='Outcome', kde=True)
plt.title('Age Distribution by Outcome')
plt.xlabel('Age')
plt.show()

# Bar plot for Outcome by Gender
sns.countplot(data=df, x='Outcome', hue='Gender')
plt.title('Outcome by Gender')
plt.show()

# Violin plot by Gender and Age
sns.violinplot(x='Outcome', y='Original_Age', hue='Gender', data=df, split=True)
plt.title('Outcome by Age and Gender')
plt.ylabel('Age')
plt.show()

# Chi-square: Gender vs Outcome
contingency_table = pd.crosstab(df['Gender'], df['Outcome'])
chi2, p, dof, expected = chi2_contingency(contingency_table)
print("\nChi-Square Test - Gender vs Outcome:")
print("Chi2 =", chi2, "P-value =", p)
print("Contingency Table:")
print(contingency_table)

# Chi-square: AgeGroup vs Outcome
contingency_table_age = pd.crosstab(df['AgeGroup'], df['Outcome'])
chi2_age, p_age, _, _ = chi2_contingency(contingency_table_age)
print("\nChi-Square Test - Age Group vs Outcome:")
print("Chi2 =", chi2_age, "P-value =", p_age)
print("Contingency Table:")
print(contingency_table_age)

# ANOVA - Age differences by Outcome
groups = [group['Original_Age'].values for name, group in df.groupby('Outcome')]
f_stat, p_val = f_oneway(*groups)
print("\nANOVA - Age by Outcome:")
print("F-statistic =", f_stat, "P-value =", p_val)

# Count plot: Outcomes by Gender within Age Groups
sns.set(style="whitegrid")
g = sns.catplot(
    data=df, kind="count",
    x="Outcome", hue="Gender",
    col="AgeGroup", palette="Set2"
)
g.fig.suptitle("Cancer Outcomes by Gender within Age Groups", y=1.05)
plt.show()

# Chi-square: Gender vs Outcome within each Age Group
age_groups = df['AgeGroup'].unique()
for group in age_groups:
    sub_df = df[df['AgeGroup'] == group]
    contingency = pd.crosstab(sub_df['Gender'], sub_df['Outcome'])
    chi2, p, dof, _ = chi2_contingency(contingency)
    print(f"\nChi-Square Test - Gender vs Outcome in Age Group '{group}':")
    print(f"Chi2 = {chi2:.3f}, p-value = {p:.4f}")
    print("Contingency Table:")
    print(contingency)

# ---------------------------------------
# Multinomial Logistic Regression (Statistical Only without using ML)
# ---------------------------------------

# Encode target variable
le = LabelEncoder()
df['Outcome_Code'] = le.fit_transform(df['Outcome'])  # e.g., Deceased=0, Recovered=1, Under Treatment=2

# Select variables
features = ['Age', 'Gender_Male']
if 'Smoking_Status_Former Smoker' in df.columns:
    features.append('Smoking_Status_Former Smoker')
if 'Smoking_Status_Smoker' in df.columns:
    features.append('Smoking_Status_Smoker')

X = df[features]
y = df['Outcome_Code']

# Fit model on entire dataset
model = LogisticRegression(solver='lbfgs', max_iter=500)
model.fit(X, y)

# Coefficients and odds ratios
coefficients = model.coef_[0]
odds_ratios = np.exp(coefficients)

coef_df = pd.DataFrame({
    'Feature': features,
    'Coefficient': coefficients,
    'Odds Ratio': odds_ratios
})

print("\nMultinomial Logistic Regression - Coefficients and Odds Ratios:")
print(coef_df)